export const IPC = {
  auth: {
    needsSetup: "auth:needsSetup",
    getSession: "auth:getSession",
    login: "auth:login",
    setupFirst: "auth:setupFirst",
    logout: "auth:logout",
    forgotPasswordGetQuestion: "auth:forgotPasswordGetQuestion",
    forgotPasswordSubmit: "auth:forgotPasswordSubmit",
    getRememberedLogin: "auth:getRememberedLogin",
    saveRememberedLogin: "auth:saveRememberedLogin",
    clearRememberedLogin: "auth:clearRememberedLogin",
    guvenlikGuncelle: "auth:guvenlikGuncelle",
    guvenlikBilgisi: "auth:guvenlikBilgisi",
    sifreGuncelle: "auth:sifreGuncelle",
  },
  app: {
    quit: "app:quit",
    getVersion: "app:getVersion",
  },
  office: {
    get: "office:get",
    save: "office:save",
    pickLogo: "office:pickLogo",
    logoDataUrl: "office:logoDataUrl",
  },
  backup: {
    al: "backup:al",
    geriYukle: "backup:geriYukle",
  },
  ofisKasa: {
    list: "ofisKasa:list",
    ustOzet: "ofisKasa:ustOzet",
    anaSayfaOzet: "ofisKasa:anaSayfaOzet",
    ekle: "ofisKasa:ekle",
    guncelle: "ofisKasa:guncelle",
    sil: "ofisKasa:sil",
    onayla: "ofisKasa:onayla",
    duzeltmeEkle: "ofisKasa:duzeltmeEkle",
    raporPaketi: "ofisKasa:raporPaketi",
  },
  muvekkil: {
    ara: "muvekkil:ara",
    araPaged: "muvekkil:araPaged",
    get: "muvekkil:get",
    ekle: "muvekkil:ekle",
    guncelle: "muvekkil:guncelle",
  },
  dosya: {
    list: "dosya:list",
    get: "dosya:get",
    ekle: "dosya:ekle",
    guncelle: "dosya:guncelle",
    hesapOzetPaketi: "dosya:hesapOzetPaketi",
  },
  kasa: {
    list: "kasa:list",
    ozet: "kasa:ozet",
    ekle: "kasa:ekle",
    guncelle: "kasa:guncelle",
    sil: "kasa:sil",
    onayla: "kasa:onayla",
  },
  vekalet: {
    getOrCreate: "vekalet:getOrCreate",
    byDosya: "vekalet:byDosya",
    kaydet: "vekalet:kaydet",
    guncelle: "vekalet:guncelle",
    taksitList: "vekalet:taksitList",
    taksitEkle: "vekalet:taksitEkle",
    taksitGuncelle: "vekalet:taksitGuncelle",
    taksitSil: "vekalet:taksitSil",
    taksitOdemeAl: "vekalet:taksitOdemeAl",
    taksitOdemeGecmisi: "vekalet:taksitOdemeGecmisi",
    smmBekleyenler: "vekalet:smmBekleyenler",
    smmKesildi: "vekalet:smmKesildi",
  },
  print: {
    getPrinters: "print:getPrinters",
    document: "print:document",
    htmlToPdf: "print:htmlToPdf",
    pdf: "print:pdf",
  },
  makbuz: {
    ensureReceiptNumber: "makbuz:ensureReceiptNumber",
    getReceiptData: "makbuz:getReceiptData",
    yazdirmaPaketi: "makbuz:yazdirmaPaketi",
  },
  vekaletMakbuz: {
    ensureReceiptNumber: "vekaletMakbuz:ensureReceiptNumber",
    getPrintPackage: "vekaletMakbuz:getPrintPackage",
    getPrintPackageByOdemeId: "vekaletMakbuz:getPrintPackageByOdemeId",
  },
  util: {
    pathToFileUrl: "util:pathToFileUrl",
  },
  license: {
    getState: "license:getState",
    activate: "license:activate",
    validate: "license:validate",
    openRenewalUrl: "license:openRenewalUrl",
  },
  masrafTurleri: "masrafTurleri",
} as const;
