export const IPC = {
  auth: {
    needsSetup: "auth:needsSetup",
    getSession: "auth:getSession",
    login: "auth:login",
    setupFirst: "auth:setupFirst",
    logout: "auth:logout",
    forgotPasswordGetQuestion: "auth:forgotPasswordGetQuestion",
    forgotPasswordSubmit: "auth:forgotPasswordSubmit",
    getRememberedLogin: "auth:getRememberedLogin",
    saveRememberedLogin: "auth:saveRememberedLogin",
    clearRememberedLogin: "auth:clearRememberedLogin",
    guvenlikGuncelle: "auth:guvenlikGuncelle",
    guvenlikBilgisi: "auth:guvenlikBilgisi",
    sifreGuncelle: "auth:sifreGuncelle",
  },
  app: {
    quit: "app:quit",
    getVersion: "app:getVersion",
  },
  office: {
    get: "office:get",
    save: "office:save",
    pickLogo: "office:pickLogo",
    logoDataUrl: "office:logoDataUrl",
  },
  appSettings: {
    getAccountingPeriodMode: "appSettings:getAccountingPeriodMode",
    setAccountingPeriodMode: "appSettings:setAccountingPeriodMode",
  },
  backup: {
    al: "backup:al",
    geriYukle: "backup:geriYukle",
  },
  ofisKasa: {
    list: "ofisKasa:list",
    ustOzet: "ofisKasa:ustOzet",
    anaSayfaOzet: "ofisKasa:anaSayfaOzet",
    ekle: "ofisKasa:ekle",
    guncelle: "ofisKasa:guncelle",
    sil: "ofisKasa:sil",
    guvenliSil: "ofisKasa:guvenliSil",
    onayla: "ofisKasa:onayla",
    duzeltmeEkle: "ofisKasa:duzeltmeEkle",
    raporPaketi: "ofisKasa:raporPaketi",
    dovizDonusum: "ofisKasa:dovizDonusum",
    dovizDonusumSil: "ofisKasa:dovizDonusumSil",
  },
  kurlar: {
    tcmb: "kurlar:tcmb",
    tcmbCapraz: "kurlar:tcmbCapraz",
    yaklasikTry: "kurlar:yaklasikTry",
  },
  muvekkil: {
    ara: "muvekkil:ara",
    araPaged: "muvekkil:araPaged",
    get: "muvekkil:get",
    ekle: "muvekkil:ekle",
    guncelle: "muvekkil:guncelle",
    karlilik: "muvekkil:karlilik",
    ofisGelirleri: "muvekkil:ofisGelirleri",
  },
  dosya: {
    list: "dosya:list",
    listAll: "dosya:listAll",
    get: "dosya:get",
    ekle: "dosya:ekle",
    guncelle: "dosya:guncelle",
    hesapOzetPaketi: "dosya:hesapOzetPaketi",
    maliOzet: "dosya:maliOzet",
    muvekkilEkstre: "dosya:muvekkilEkstre",
  },
  kasa: {
    list: "kasa:list",
    ozet: "kasa:ozet",
    ekle: "kasa:ekle",
    guncelle: "kasa:guncelle",
    sil: "kasa:sil",
    guvenliSil: "kasa:guvenliSil",
    onayla: "kasa:onayla",
  },
  tahsilatMerkezi: {
    ozet: "tahsilatMerkezi:ozet",
    list: "tahsilatMerkezi:list",
  },
  icraTahsilat: {
    ustOzet: "icraTahsilat:ustOzet",
    list: "icraTahsilat:list",
    alacakOlustur: "icraTahsilat:alacakOlustur",
    taksitList: "icraTahsilat:taksitList",
    taksitOdemeAl: "icraTahsilat:taksitOdemeAl",
    taksitOdemeGecmisi: "icraTahsilat:taksitOdemeGecmisi",
    taksitSil: "icraTahsilat:taksitSil",
    taksitGuncelle: "icraTahsilat:taksitGuncelle",
    smmKesildi: "icraTahsilat:smmKesildi",
    alacakIptal: "icraTahsilat:alacakIptal",
  },
  vekalet: {
    getOrCreate: "vekalet:getOrCreate",
    byDosya: "vekalet:byDosya",
    kaydet: "vekalet:kaydet",
    guncelle: "vekalet:guncelle",
    taksitList: "vekalet:taksitList",
    taksitEkle: "vekalet:taksitEkle",
    taksitGuncelle: "vekalet:taksitGuncelle",
    taksitSil: "vekalet:taksitSil",
    taksitleriTopluSil: "vekalet:taksitleriTopluSil",
    taksitOdemeAl: "vekalet:taksitOdemeAl",
    taksitOdemeGuncelle: "vekalet:taksitOdemeGuncelle",
    taksitOdemeGecmisi: "vekalet:taksitOdemeGecmisi",
    smmBekleyenler: "vekalet:smmBekleyenler",
    smmKesildi: "vekalet:smmKesildi",
    taksitUyariOzet: "vekalet:taksitUyariOzet",
    guvenliSilTaksit: "vekalet:guvenliSilTaksit",
    guvenliSilTahsilat: "vekalet:guvenliSilTahsilat",
  },
  print: {
    getPrinters: "print:getPrinters",
    document: "print:document",
    htmlToPdf: "print:htmlToPdf",
    pdf: "print:pdf",
  },
  makbuz: {
    ensureReceiptNumber: "makbuz:ensureReceiptNumber",
    getReceiptData: "makbuz:getReceiptData",
    yazdirmaPaketi: "makbuz:yazdirmaPaketi",
  },
  vekaletMakbuz: {
    ensureReceiptNumber: "vekaletMakbuz:ensureReceiptNumber",
    getPrintPackage: "vekaletMakbuz:getPrintPackage",
    getPrintPackageByOdemeId: "vekaletMakbuz:getPrintPackageByOdemeId",
  },
  util: {
    pathToFileUrl: "util:pathToFileUrl",
    openContactLink: "util:openContactLink",
  },
  license: {
    getState: "license:getState",
    activate: "license:activate",
    validate: "license:validate",
    startTrial: "license:startTrial",
    openRenewalUrl: "license:openRenewalUrl",
  },
  update: {
    getStatus: "update:getStatus",
    check: "update:check",
    download: "update:download",
    install: "update:install",
    dismiss: "update:dismiss",
    statusChanged: "update:statusChanged",
  },
  masrafTurleri: "masrafTurleri",
  finansKalemi: {
    list: "finansKalemi:list",
    create: "finansKalemi:create",
    update: "finansKalemi:update",
    archive: "finansKalemi:archive",
    activate: "finansKalemi:activate",
    reorder: "finansKalemi:reorder",
  },
  audit: {
    list: "audit:list",
  },
  kullaniciYonetim: {
    list: "kullaniciYonetim:list",
    create: "kullaniciYonetim:create",
    setAktif: "kullaniciYonetim:setAktif",
    resetSifre: "kullaniciYonetim:resetSifre",
  },
  randevu: {
    list: "randevu:list",
    get: "randevu:get",
    olustur: "randevu:olustur",
    guncelle: "randevu:guncelle",
    sil: "randevu:sil",
    kullanicilar: "randevu:kullanicilar",
  },
  maliKontrol: {
    uyarilar: "maliKontrol:uyarilar",
  },
} as const;
